#!/usr/bin/env bash

echo -e "Sleep\nShutdown\nReboot" | rofi -dmenu \
-bw 2 \
-p "" \
-width 11 \
-columns 1 \
-location 3 \
-kb-row-tab "" \
-line-margin 0 \
-font "mono 10" \
-hide-scrollbar \
-line-padding 1 \
-disable-history \
-kb-row-select "Tab" \
-separator-style none \
-color-window "argb:00000000, argb:00000000, #b1b4b3" \
-color-active "argb:00000000, argb:99b1b4b3, argb:00000000, #77003d, argb:ffffffff" \
-color-normal "argb:00000000, argb:99b1b4b3, argb:00000000, #77003d, argb:ffffffff" \
-color-urgent "argb:00000000, argb:99b1b4b3, argb:00000000, #77003d, argb:ffffffff" | 
while read value; do
    # something
   if [ $value == "Sleep" ]
      then 
      dm-tool lock
   elif [ $value == "Shutdown" ]
       then
       systemctl poweroff
   elif [ $value == "Reboot" ]
       then
       systemctl reboot
   else
      echo "Quit"
   fi
done

