require("gobllm")
require("functions")

vim.api.nvim_create_user_command('D', daily_note, {})
vim.api.nvim_create_user_command('Cd', change_dir, {})
vim.api.nvim_create_user_command('In', open_inbox, {})
vim.api.nvim_create_user_command('Vf', vault_file, {})
vim.api.nvim_create_user_command('Df', delete_file, {})
vim.api.nvim_create_user_command('Va', vault_folder, {})
vim.api.nvim_create_user_command('Jo', journal_folder, {})
vim.api.nvim_create_user_command('Dn', next_daily_note, {})
vim.api.nvim_create_user_command('Dp', previous_daily_note, {})
vim.api.nvim_create_user_command('Nn', new_note, { nargs = '*'})
vim.api.nvim_create_user_command('Rf', rename_file, { nargs = '*'})
vim.api.nvim_create_user_command('SortByWidth', sort_by_width, { range = true })
vim.api.nvim_create_user_command('SortByWidth', sort_by_width, { range = true })
vim.api.nvim_create_user_command('OpenDates', OpenDates, { range = true })
